install.sh

Add's support to the installer for the fish shell.
Part of #4.

Support for fish shell.

---

data/007.json

Added more quotes to data.
Adds to https://github.com/mubaris/motivate/issues/3

Data: Add motivational quotes

---

data/008.json

Added another pack of quotes, I hope y'all like them :)

Added more quotes

---

data/008.json

Added 20 more quotes. 
Relted to #3

Add more quotes

---

install.sh

xonsh shell support

---

find_dupes.py

I have noticed you have a few duplicates so I wrote a small duplicate printing script. Nothing fancy as I am no Python guru. It is not a problem but might come in handy when adding more quotes.

Add a utility script to print duplicates

---

data/011.json

Hi! This is my first ever Github pull request. I found this project through Hacktoberfest. Thanks for making it up for grabs!

Added 25 awesome quotes!

---

data/012.json

Added a bunch of motivational quotes from artists

added 012.json

---

install.sh

Global Installation

---

data/013.json

Hi all,
This is my first contribution. Please check and let me know if I have to change something.
Regards,
Dhanya

Added new quotes

---

data/014.json

Add a new quote file

---

motivate/data/020.json

Added 20 more motivational quotes via 020.json.

Adding 020.json

---

motivate/data/021.json

Created 021.json

---

motivate/motivate.py

The cmd line colour used to turn into pink after the print function. Now the cmd line colour changes to white after printing the quote and the author.

Cmd line colour changes back to white 

---

motivate/data/089.json

Add new unique quotes

---

README.md

Minor fix in the README, as the install script is inside the motivate/motivate/ directory

Minor fix in the README

---

motivate/data/100.json
motivate/data/101.json

"Please verify that my PR follows all the rules and pull into the master branch accordingly".

Added the 101'st file

---

motivate/data/103.json

add 103.json file

---

motivate/data/111.json

Create 111.json with 20 quotes

---

motivate/data/116.json

More new quotes

---

motivate/data/117.json

117.json contains 20 more motivational quotes.

Adds 117.json to data

---

motivate/data/120.json

Added a json files with Jack Ma's quotes. (120.json)

Add JackMa's Quotes

---

motivate/data/121.json

Added Soichiro Honda's Quotes as a json file(121.json)

Add Soichiro Honda's Quotes

---

motivate/data/122.json

Add Albert Einstein's Quotes as json file.(122.json)

Add Albert Einstein's Quotes

---

motivate/data/123.json
motivate/data/124.json

Add 2 files of Robin Sharma's Quotes.

Add Robin Sharma Quotes

---

motivate/data/125.json
motivate/data/126.json
motivate/data/127.json
motivate/data/128.json
motivate/data/129.json

Added 5 json files of Robin Sharma's Quotes.

Add 100 Robin Sharma's Quotes

---

motivate/data/131.json

They are in the 131.json file :-)

New quotes added.

---

motivate/data/134.json

Taken from various sources from Internet and my own contribution too.
json has been verified from given website

Added 20 quotes

---

motivate/data/136.json
motivate/data/138.json
motivate/data/141.json

Error resolved

---

motivate/data/143.json

Added a new JSON file

---

motivate/data/144.json

I have included 20 motivation quotes and placed it in a file called: **144.json**.
Let me know if this looks good or if you have any issues with it.  Thanks! :)

added new JSON file

---

motivate/data/145.json

Added Quotes

---

motivate/data/135.json
motivate/data/147.json
motivate/data/148.json

135.json is failing is JSONLint and gives error on terminal. So I have formatted it correctly

New Quotes and JSON formatted correctly

---

motivate/data/150.json

This is my first PR ever, I hope i did everything right.

added 20 new quotes

---

motivate/data/151.json

adding 20 more quotes into 151.json

adding 20 more quotes

---

motivate/data/153.json

Added 20 Quotes to the file 153.json

Added json file 153

---

motivate/data/154.json

Added a json file with more quotes

More quotes

---

motivate/data/156.json

My humble contribution to the project. I hope you like it!

156.json added with buddhist quotes from Pema Chodron.

---

motivate/data/161.json
motivate/data/163.json

Added 163.json and also fixed some formatting issues that were causing issue #144

Added new quotes and fixed issue #144

---

motivate/txt_to_json.py

Hello,
I'm proposing an utilitary to parse a txt file to the json format to make contributions easier
The file must be in the following format
"quote1",Author
"quote2",Other Author
To run: python quotes_to_json.py
If the quotes file is not named quotes.txt them run: python quotes_to_json.py --file="File name"

Proposing a quotes txt to json parser

---

.gitignore
motivate/data/166.json

Please let me know if I need to make any changes or if these look ok to merge. Thanks again!

New quotes for the project. Thanks for letting me participate!

---

motivate/data/170.json

20 Inspirational Terry Pratchett Quotes in JSON format

20 Terry Pratchett Quotes

---

motivate/data/173.json

Added art related quotes

---

motivate/data/176.json

20 quotes from composers and musicians from various time periods, ran through the website in the README with no issues. Thank you!

added quotes mainly from composers and musicians

---

motivate/data/177.json

Just added my share of 20 quotes which I picked from common quotes in the Civilization 5 game

Added 177 json filled with Civ 5 quotes

---

motivate/data/178.json

20 Powerful Quotes(my first commit)

---

motivate/data/179.json

20 translated quotes from manga/anime/kpop

added 179.json

---

motivate/data/180.json

I validated it with the JSON validating website that you provided.  This is my first contribution, so please let me know if there are any issues that I need to resolve.
- Zach

Added some quotes in the 180.json file.
